# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='avatars/default.jpg', upload_to='images/'),
        ),
    ]
